"""Contract and legal synonym groups used by keyword retrieval.

Keep this vocabulary separate from the RAG logic so it is easy to maintain.
"""

SYNONYM_GROUPS = [
    {
        'pay',
        'اجر',
        'wage',
        'راتب',
        'مرتب',
        'الأجر',
        'الاجر',
        'تعويض',
        'salary',
        'الأجور',
        'الراتب',
        'المرتب',
        'payment',
        'التعويض',
        'المقابل',
        'compensation',
        'remuneration',
    },

    {
        'bonus',
        'perks',
        'حوافز',
        'مزايا',
        'مكافآت',
        'مكافأة',
        'benefit',
        'bonuses',
        'الحوافز',
        'المزايا',
        'benefits',
        'المكافآت',
        'المكافأة',
        'امتيازات',
        'allowance',
        'incentive',
        'allowances',
        'incentives',
        'الامتيازات',
    },

    {
        'عامل',
        'موظف',
        'staff',
        'worker',
        'العامل',
        'الموظف',
        'employee',
        'العاملين',
        'المستخدم',
        'الموظفين',
        'employees',
        'personnel',
        'المستخدمين',
    },

    {
        'صاحب',
        'الجهة',
        'الطرف',
        'العمل',
        'الشركة',
        'company',
        'المؤسسة',
        'business',
        'employer',
        'صاحب العمل',
        'organisation',
        'organization',
    },

    {
        'عقد',
        'deal',
        'اتفاق',
        'العقد',
        'اتفاقية',
        'الاتفاق',
        'التعاقد',
        'contract',
        'المعاهدة',
        'agreement',
        'الاتفاقية',
        'التعاقدات',
        'عقد العمل',
        'employment contract',
        'employment agreement',
    },

    {
        'job',
        'work',
        'العمل',
        'hiring',
        'التشغيل',
        'التعيين',
        'التوظيف',
        'العمالة',
        'الوظيفة',
        'employment',
        'appointment',
    },

    {
        'role',
        'title',
        'الدور',
        'المسمى',
        'المنصب',
        'المهام',
        'الوظيفة',
        'position',
        'الاختصاص',
        'job title',
        'responsibility',
        'المسمى الوظيفي',
        'responsibilities',
    },

    {
        'duty',
        'مهمة',
        'tasks',
        'duties',
        'المهام',
        'واجبات',
        'التزامات',
        'الواجبات',
        'مسؤوليات',
        'الالتزامات',
        'المسؤوليات',
        'obligations',
        'responsibility',
        'responsibilities',
    },

    {
        'دوام',
        'hours',
        'العمل',
        'ساعات',
        'الدوام',
        'schedule',
        'وقت العمل',
        'work hours',
        'ساعات العمل',
        'working time',
        'مواعيد العمل',
        'working hours',
    },

    {
        'الدوام',
        'workdays',
        'يوم العمل',
        'أيام العمل',
        'أيام الدوام',
        'working days',
        'business days',
    },

    {
        'راحة',
        'عطلة',
        'leave',
        'إجازة',
        'اجازة',
        'الراحة',
        'holiday',
        'الإجازة',
        'العطلات',
        'holidays',
        'vacation',
        'الإجازات',
        'الاجازات',
        'annual leave',
        'annual vacation',
        'الإجازة السنوية',
        'الإجازات السنوية',
    },

    {
        'المرض',
        'مرضية',
        'المرضية',
        'sick days',
        'sick leave',
        'medical leave',
        'الإجازة المرضية',
        'الإجازات المرضية',
    },

    {
        'التجربة',
        'الاختبار',
        'probation',
        'trial period',
        'تحت الاختبار',
        'فترة التجربة',
        'فترة الاختبار',
        'probation period',
    },

    {
        'term',
        'المدة',
        'period',
        'duration',
        'مدة العقد',
        'مدة العمل',
        'سريان العقد',
        'مدة التعاقد',
        'contract term',
        'مدة الاتفاقية',
        'contract duration',
    },

    {
        'بدء العمل',
        'start date',
        'تاريخ البدء',
        'starting date',
        'تاريخ البداية',
        'تاريخ التعيين',
        'تاريخ الالتحاق',
        'commencement date',
        'employment start date',
    },

    {
        'expiry',
        'end date',
        'expiration',
        'انتهاء العقد',
        'انتهاء المدة',
        'انقضاء العقد',
        'تاريخ النهاية',
        'تاريخ الانتهاء',
        'end of contract',
        'expiration date',
    },

    {
        'فسخ',
        'إنهاء',
        'الفصل',
        'انهاء',
        'rescind',
        'الإنهاء',
        'الانهاء',
        'dismissal',
        'terminate',
        'فسخ العقد',
        'termination',
        'إنهاء العقد',
        'انهاء العقد',
        'cancellation',
        'termination of contract',
    },

    {
        'quit',
        'resign',
        'استقالة',
        'الاستقال',
        'الانسحاب',
        'الاستقالة',
        'ترك العمل',
        'resignation',
    },

    {
        'إشعار',
        'notice',
        'الإخطار',
        'إخطار مسبق',
        'إشعار مسبق',
        'مدة الإخطار',
        'prior notice',
        'فترة الإخطار',
        'notice period',
        'advance notice',
    },

    {
        'nda',
        'سرية',
        'السرية',
        'عدم الإفصاح',
        'confidential',
        'non disclosure',
        'non-disclosure',
        'سرية المعلومات',
        'confidentiality',
        'البيانات السرية',
        'المعلومات السرية',
    },

    {
        'ip',
        'patent',
        'الفكرية',
        'الملكية',
        'البراءات',
        'copyright',
        'حقوق النشر',
        'حقوق التأليف',
        'الملكية الفكرية',
        'ownership rights',
        'حقوق الملكية الفكرية',
        'intellectual property',
    },

    {
        'المنافسة',
        'non compete',
        'non-compete',
        'حظر المنافسة',
        'عدم المنافسة',
        'شرط عدم المنافسة',
        'competition restriction',
    },

    {
        'solicitation',
        'حظر الاستقطاب',
        'عدم الاستقطاب',
        'عدم جذب العملاء',
        'non solicitation',
        'non-solicitation',
        'استقطاب الموظفين',
    },

    {
        'law',
        'laws',
        'rules',
        'سياسة',
        'policy',
        'الأنظمة',
        'اللائحة',
        'اللوائح',
        'policies',
        'الامتثال',
        'السياسات',
        'القوانين',
        'compliance',
        'regulations',
        'سياسة الشركة',
    },

    {
        'الخلاف',
        'النزاع',
        'dispute',
        'conflict',
        'disputes',
        'الخلافات',
        'النزاعات',
        'المنازعات',
        'حل النزاع',
        'settlement',
        'تسوية النزاع',
        'dispute resolution',
    },

    {
        'court',
        'courts',
        'الدعوى',
        'القضاء',
        'lawsuit',
        'التقاضي',
        'المحاكم',
        'المحكمة',
        'litigation',
        'الجهات المختصة',
        'المحكمة المختصة',
        'legal proceedings',
    },

    {
        'law',
        'التشريع',
        'القانون',
        'القوانين',
        'التشريعات',
        'legislation',
        'governing law',
        'applicable law',
        'القانون المعمول به',
        'القانون الواجب التطبيق',
    },

    {
        'liability',
        'المسؤولية',
        'المسؤوليات',
        'responsibility',
        'civil liability',
        'legal liability',
        'المسؤولية المدنية',
        'المسؤولية القانونية',
    },

    {
        'خرق',
        'breach',
        'انتهاك',
        'مخالفة',
        'default',
        'الإخلال',
        'المخالفة',
        'violation',
        'خرق العقد',
        'الإخلال بالعقد',
        'breach of contract',
    },

    {
        'due',
        'دفعة',
        'الدفع',
        'payable',
        'payment',
        'payments',
        'المستحقات',
        'amount due',
        'الدفع المستحق',
        'المبلغ المستحق',
    },

    {
        'بدل',
        'بدلات',
        'expense',
        'النفقات',
        'expenses',
        'المصاريف',
        'allowance',
        'المصروفات',
        'reimbursement',
    },

    {
        'ملحق',
        'amend',
        'تغيير',
        'change',
        'التعديل',
        'addendum',
        'amendment',
        'التغييرات',
        'ملحق العقد',
        'تعديل العقد',
        'modification',
    },

    {
        'renew',
        'تمديد',
        'renewal',
        'التجديد',
        'extension',
        'تجديد العقد',
        'تمديد العقد',
        'التجديد التلقائي',
        'automatic renewal',
    },

    {
        'assign',
        'التفويض',
        'التنازل',
        'transfer',
        'assignment',
        'تحويل العقد',
        'التنازل عن العقد',
    },

    {
        'تمثيل',
        'الضمان',
        'الإقرار',
        'warranty',
        'الضمانات',
        'الإقرارات',
        'warranties',
        'representation',
        'representations',
    },

    {
        'act of god',
        'force majeure',
        'القوة القاهرة',
        'الظروف الطارئة',
        'الظروف القاهرة',
        'unforeseen circumstances',
    },

    {
        'privacy',
        'البيانات',
        'الخصوصية',
        'personal data',
        'حماية البيانات',
        'data protection',
        'البيانات الشخصية',
        'المعلومات الشخصية',
        'personal information',
    },

]
